### ISSUE TITLE
Dedicated Serverside Crash - seems to be calling clientside code serverside.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [coderbot16/ProjectY#9]
https://gist.github.com/P3rf3ctXZer0/dc2f9f46f6edc6ed89556a14460ddff5

**Comment by coderbot16** [comment]
Looks like it’s because I don’t test the mods on the server side. I probably need some @SideOnly annotations or a clientproxy.

**Comment by coderbot16** [comment]
Fixed in https://github.com/coderbot16/Quartzium/commit/aa957a57f3e0b834b3e12888c4f7619f5efcd122 - available on CurseForge at https://minecraft.curseforge.com/projects/quartzium/files/2692160
